### ISSUE TITLE
RaMS v1.3.2

### ISSUE THREAD

**Issue by wkumler** [wkumler/RaMS#23]
To-do and progress list here:

- [x] Add `arrow` vignette
- [x] Fix OpenChrom namespacing (#17, #18)
- [ ] Add multiscan code (#20)
- [x] Add a filetype check before loading files (#21)
- [x] Add convenience functions (#22)
- [x] Update NEWS
- [x] Check documentation looks ok when rendered
- [x] Update README
- [x] Push to CRAN
