### ISSUE TITLE
RaMS v 1.4

### ISSUE THREAD

**Issue by wkumler** [wkumler/RaMS#32]
Checklist for RaMS version 1.4 below:

- [x] Update NEWS with 1.3.4 stuff (#30 )
- [x] Add references to R Journal paper (#29 )
- [x] Fix RT unit extraction for BPCs (#28 ) 
- [x] Fix filepaths to Metabolights - update to MetabolomicsWorkbench? (#27 )
- [x] Add retention time editing
- [x] Add MS3 extraction
- [x] Add tests and merge incl_polarity option
- [x] Update DESCRIPTION and NEWS for 1.4
- [x] Push to CRAN

**Comment by wkumler** [comment]
Finalized with #33
